#cloud-config
package_update: true

users:
  - default
  - name: slurmadmin
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_public_key}

write_files:
  - path: /home/slurmadmin/.ssh/authorized_keys
    defer: true
    owner:
      name: slurmadmin
      group: slurmadmin
    permissions: "0600"
    content: |
      ${ssh_public_key}

packages:
  - munge

runcmd:
  - [ bash, -lc, "install -d -m 755 /opt/slurm-hybrid /etc/slurm" ]
